/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ord;

/**
 *
 * @author Noor Aldeen Muneer
 */
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class order extends javax.swing.JFrame {
private FileReader fr;
private FileWriter fw;
    /**
     * Creates new form order
     */
    public order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtitem = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        jtxtdescribtion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtorderdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtordertime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtquantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtunitprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtorderid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtcustomername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtcustomerphone = new javax.swing.JTextField();
        butsave = new javax.swing.JButton();
        butsearch = new javax.swing.JButton();
        butdelete = new javax.swing.JButton();
        butupdate = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        RTIJTF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordere");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Item");

        jlabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel2.setText("Describtion");

        jtxtdescribtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdescribtionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Order Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Order Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Unit Price");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Order Id");

        jtxtorderid.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Customer Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Customer Phone");

        butsave.setBackground(new java.awt.Color(153, 255, 255));
        butsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butsave.setText("Save");
        butsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsaveActionPerformed(evt);
            }
        });

        butsearch.setBackground(new java.awt.Color(153, 255, 255));
        butsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butsearch.setText("Search");
        butsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsearchActionPerformed(evt);
            }
        });

        butdelete.setBackground(new java.awt.Color(153, 255, 255));
        butdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butdelete.setText("Delete");
        butdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdeleteActionPerformed(evt);
            }
        });

        butupdate.setBackground(new java.awt.Color(153, 255, 255));
        butupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butupdate.setText("Update");
        butupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butupdateActionPerformed(evt);
            }
        });

        jCheckBox1.setText("editable Order Id");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        RTIJTF.setText("remove text inside text filed");
        RTIJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTIJTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(jtxtorderid)
                                            .addComponent(jtxtcustomername)
                                            .addComponent(jtxtcustomerphone))
                                        .addComponent(jtxtitem, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtorderdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtordertime, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxtunitprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtdescribtion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(butdelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(butsave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCheckBox1))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RTIJTF)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(butupdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(butsearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtcustomerphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtdescribtion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtorderdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtordertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butsave)
                    .addComponent(butsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butdelete)
                    .addComponent(butupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RTIJTF)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtdescribtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdescribtionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdescribtionActionPerformed

    private void butsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsaveActionPerformed
            // TODO add your handling code here:
          
                try {
                    ArrayList<String []> al= ALoforder();
                    int orid=500;
                    if(al.size()>0){
                    orid=Integer.parseInt(al.get(al.size()-1)[0])+1;}
                    else orid=1;
                    jtxtorderid.setText(""+orid);
                    fw=new FileWriter("ordere.txt",true);//File Name
                    String s=jtxtorderid.getText()+","+jtxtitem.getText()+","+jtxtcustomername.getText()+","+jtxtcustomerphone.getText()+","+jtxtdescribtion.getText()
                            +","+jtxtquantity.getText()+","+jtxtunitprice.getText()+","+jtxtorderdate.getText()+","+jtxtordertime.getText()+"\n";
                    fw.append(s);
                    fw.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,"Input Output Exception");
                }
    }//GEN-LAST:event_butsaveActionPerformed

    private void butsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsearchActionPerformed
        // TODO add your handling code here:
       ArrayList<String []> al= ALoforder();
       int flag=0,fl=0,fo=0;
       String []Q=new String[9];
       Q[0]=jtxtorderid.getText(); Q[1]=jtxtitem.getText(); Q[2]=jtxtcustomername.getText();
       Q[3]=jtxtcustomerphone.getText(); Q[4]=jtxtdescribtion.getText(); Q[5]=jtxtquantity.getText();
       Q[6]=jtxtunitprice.getText(); Q[7]=jtxtorderdate.getText(); Q[8]=jtxtordertime.getText();
       for(int i=0;i<9;i++){
       for(int j=0;j<9;j++){
       if(i!=j&&(!Q[i].isEmpty())&&(!Q[j].isEmpty())){
       flag=1;
       for(int y=0;y<al.size();y++){
          if(al.get(y)[i].equals(Q[i])&&al.get(y)[j].equals(Q[j])){
          jtxtorderid.setText(al.get(y)[0]); jtxtitem.setText(al.get(y)[1]);jtxtcustomername.setText(al.get(y)[2]);
      jtxtcustomerphone.setText(al.get(y)[3]); jtxtdescribtion.setText(al.get(y)[4]); jtxtquantity.setText(al.get(y)[5]);
       jtxtunitprice.setText(al.get(y)[6]); jtxtorderdate.setText(al.get(y)[7]); jtxtordertime.setText(al.get(y)[8]);
       fl=1;
       break;
          }
       }
       fo=1;break;
       }
       if(fl==1)break;
       }
       if(fl==1||fo==1)break;
       }
       if(fl==0&&flag==1) JOptionPane.showMessageDialog(null,"order Not found");
    if(flag==0){
        int dr=0;
     for(int j=0;j<9;j++){
       if((!Q[j].isEmpty())){
         for(int y=0;y<al.size();y++){
          if(al.get(y)[j].equals(Q[j])){
          jtxtorderid.setText(al.get(y)[0]); jtxtitem.setText(al.get(y)[1]);jtxtcustomername.setText(al.get(y)[2]);
      jtxtcustomerphone.setText(al.get(y)[3]); jtxtdescribtion.setText(al.get(y)[4]); jtxtquantity.setText(al.get(y)[5]);
       jtxtunitprice.setText(al.get(y)[6]); jtxtorderdate.setText(al.get(y)[7]); jtxtordertime.setText(al.get(y)[8]);
       dr=1;
       break;
          }
       }
       }
        if(dr==1)break;
    }
      if(dr==0&&flag==0) JOptionPane.showMessageDialog(null,"order Not found");
    }
    }//GEN-LAST:event_butsearchActionPerformed

    private void butdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdeleteActionPerformed
        // TODO add your handling code here:
        String id=jtxtorderid.getText();
        int aa=-1;
         ArrayList<String []> al= ALoforder();
         for(int i=0;i<al.size();i++){
         if(al.get(i)[0].equals(id)){aa=i;}
         }
         al.remove(aa);
    try {
        fw=new FileWriter("ordere.txt");
        String s="";
        for(int i=0;i<al.size();i++){
        s+=al.get(i)[0]+","+al.get(i)[1]+","+al.get(i)[2]+","+al.get(i)[3]+","+al.get(i)[4]+","+al.get(i)[5]+","
                +al.get(i)[6]+","+al.get(i)[7]+","+al.get(i)[8]+"\n";
        }
        fw.write(s);
        fw.close();
    } catch (IOException ex) {
         JOptionPane.showMessageDialog(null,"Input Output Exception");
    }
    }//GEN-LAST:event_butdeleteActionPerformed

    private void butupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butupdateActionPerformed
        // TODO add your handling code here:
                String id=jtxtorderid.getText();
        int aa=-1;
         ArrayList<String []> al= ALoforder();
         for(int i=0;i<al.size();i++){
         if(al.get(i)[0].equals(id)){aa=i;}
         }
         al.get(aa)[0]=jtxtorderid.getText();al.get(aa)[1]=jtxtitem.getText();al.get(aa)[2]=jtxtcustomername.getText();
         al.get(aa)[3]=jtxtcustomerphone.getText();al.get(aa)[4]=jtxtdescribtion.getText();
         al.get(aa)[5]=jtxtquantity.getText();al.get(aa)[6]=jtxtunitprice.getText();
         al.get(aa)[7]=jtxtorderdate.getText();al.get(aa)[8]=jtxtordertime.getText();
    try {
        fw=new FileWriter("ordere.txt");
        String s="";
        for(int i=0;i<al.size();i++){
        s+=al.get(i)[0]+","+al.get(i)[1]+","+al.get(i)[2]+","+al.get(i)[3]+","+al.get(i)[4]+","+al.get(i)[5]+","
                +al.get(i)[6]+","+al.get(i)[7]+","+al.get(i)[8]+"\n";
        }
        fw.write(s);
        fw.close();
    } catch (IOException ex) {
          JOptionPane.showMessageDialog(null,"Input Output Exception");
    }
    }//GEN-LAST:event_butupdateActionPerformed

    private void RTIJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTIJTFActionPerformed
        // TODO add your handling code here:
        jtxtorderid.setText(""); jtxtitem.setText(""); jtxtcustomername.setText("");jtxtcustomerphone.setText("");
        jtxtdescribtion.setText(""); jtxtquantity.setText("");jtxtunitprice.setText("");jtxtorderdate.setText("");jtxtordertime.setText("");
    }//GEN-LAST:event_RTIJTFActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())jtxtorderid.setEditable(true);
        else jtxtorderid.setEditable(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    private ArrayList<String []> ALoforder(){
          ArrayList<String []> a=new ArrayList<String []>();
    try {
        fr=new FileReader("ordere.txt");
        String[] s=new String[9];
        Scanner sc=new Scanner(fr);
        while(sc.hasNextLine()){
        String str=sc.nextLine();
        s=str.split(",");
        a.add(s);
        s=new String[9];
        }
    } catch (FileNotFoundException ex) {
        
    }
        return a;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RTIJTF;
    private javax.swing.JButton butdelete;
    private javax.swing.JButton butsave;
    private javax.swing.JButton butsearch;
    private javax.swing.JButton butupdate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTextField jtxtcustomername;
    private javax.swing.JTextField jtxtcustomerphone;
    private javax.swing.JTextField jtxtdescribtion;
    private javax.swing.JTextField jtxtitem;
    private javax.swing.JTextField jtxtorderdate;
    private javax.swing.JTextField jtxtorderid;
    private javax.swing.JTextField jtxtordertime;
    private javax.swing.JTextField jtxtquantity;
    private javax.swing.JTextField jtxtunitprice;
    // End of variables declaration//GEN-END:variables
}
